### ISSUE TITLE
testnet is stuck/halted at block 2050181

### ISSUE THREAD

**Issue by ybstaked** [provenance-io/testnet#22]
Stuck since 2021/07/02 05:19:45+UTC: https://explorer.test.provenance.io/blocks

**Comment by SpicyLemon** [comment]
https://explorer.test.provenance.io/network/upgrades

Upgrade [desert](https://github.com/provenance-io/provenance/releases/tag/v1.5.0) occurred at block `2050181` which halted the chain so that nodes could switch to `provenanced` version `v1.5.0`.
